# Java Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service
  labels:
    app: java-service
spec:
  replicas: 1  # Start with 1 replica for debugging
  selector:
    matchLabels:
      app: java-service
  template:
    metadata:
      labels:
        app: java-service
    spec:
      containers:
      - name: java-service
        image: lookatravi/java-service:v6
        #command: ["sh", "-c", "java -jar /app/java-service.jar --server.servlet.context-path=/api/java"]
        #command: ["sh", "-c", "java -jar /app/java-service.jar"]
        command: ["java", "-jar", "app.jar"] 
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe: 
           httpGet:
             path: /api/java/health
             port: 8080
           initialDelaySeconds: 60
        readinessProbe:
           httpGet:
             path: /api/java/health
             port: 8080
           initialDelaySeconds: 30
---