apiVersion: v1
kind: Service
metadata:
  name: java-service
  labels:
    app: java-service
spec:
  selector:
    app: java-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP