version: '3'
services:
  java-service:
    image: java-service:latest
    build:
      context: ./java-service
    ports:
      - "8080:8080"
    networks:
      - devops-network

  python-service:
    image: python-service:latest
    build:
      context: ./python-service
    ports:
      - "5001:5000"
    networks:
      - devops-network

  go-service:
    image: go-service:latest
    build:
      context: ./go-service
    ports:
      - "5002:5002"
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
