apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  labels:
    app: go-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
      - name: go-service
        image: lookatravi/go-service:v1
        ports:
        - containerPort: 5002
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        #livenessProbe:
        #  httpGet:
        #    path: /api/go/health
        #    port: 5002
        #  initialDelaySeconds: 30
        #  periodSeconds: 10
        #readinessProbe:
        #  httpGet:
        #    path: /api/go/health
        #    port: 5002
        #  initialDelaySeconds: 5s
        #  periodSeconds: 10