apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python-service
spec:
  selector:
    app: python-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP