name: multi-lang-devops-ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:

  build-java-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Java Service
      run: |
        cd java-service
        ./mvnw clean package

    - name: Unit Test Java Service
      run: |
        cd java-service
        ./mvnw test

  build-python-service:
    runs-on: ubuntu-latest
    needs: build-java-service   # 🛑 Waits for Java build to finish
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd python-service
        pip install -r requirements.txt

    - name: Unit Test Python Service
      run: |
        cd python-service
        pytest

  build-go-service:
    runs-on: ubuntu-latest
    needs: build-python-service   # 🛑 Waits for Python build to finish
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build Go Service
      run: |
        cd go-service
        go mod download
        go build -o go-service main.go

    - name: Unit Test Go Service
      run: |
        cd go-service
        go test ./...

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-go-service    # 🛑 Waits for Go build to finish

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build & Push Java Service Image
      uses: docker/build-push-action@v6
      with:
        context: java-service
        file: java-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/java-service:${{ github.run_id }}

    - name: Build & Push Python Service Image
      uses: docker/build-push-action@v6
      with:
        context: python-service
        file: python-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/python-service:${{ github.run_id }}

    - name: Build & Push Go Service Image
      uses: docker/build-push-action@v6
      with:
        context: go-service
        file: go-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/go-service:${{ github.run_id }}

  update-k8s-manifests:
    runs-on: ubuntu-latest
    needs: docker-build-push    # 🛑 Waits for docker push to complete

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Kubernetes Manifests
      run: |
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/java-service:${{ github.run_id }}|" kubernetes/java-service/deploy.yaml
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/python-service:${{ github.run_id }}|" kubernetes/python-service/deploy.yaml
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/go-service:${{ github.run_id }}|" kubernetes/go-service/deploy.yaml

    - name: Commit and Push Manifest Changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add kubernetes/java-service/deploy.yaml kubernetes/python-service/deploy.yaml kubernetes/go-service/deploy.yaml
        git commit -m "[CI]: Update image tags for Java, Python, and Go services"
        git push origin HEAD:main -f
