name: multi-lang-devops-ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-java-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Java Service
      run: |
        cd java-service
        ./mvnw clean package

    - name: Unit Test Java Service
      run: |
        cd java-service
        ./mvnw test

  build-python-service:
    runs-on: ubuntu-latest
    needs: build-java-service
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        cd python-service
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Unit Test Python Service
      run: |
        cd python-service
        pytest test_app.py

  build-go-service:
    runs-on: ubuntu-latest
    needs: build-python-service
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build Go Service
      run: |
        cd go-service
        go mod download
        go build -o go-service main.go

    - name: Unit Test Go Service
      run: |
        cd go-service
        go test ./...

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-go-service
    env:
      DOCKER_USERNAME: lookatravi
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build & Push Java Service Image
      uses: docker/build-push-action@v6
      with:
        context: java-service
        file: java-service/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/java-service:${{ github.run_id }}
          ${{ env.DOCKER_USERNAME }}/java-service:latest

    - name: Build & Push Python Service Image
      uses: docker/build-push-action@v6
      with:
        context: python-service
        file: python-service/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/python-service:${{ github.run_id }}
          ${{ env.DOCKER_USERNAME }}/python-service:latest

    - name: Build & Push Go Service Image
      uses: docker/build-push-action@v6
      with:
        context: go-service
        file: go-service/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/go-service:${{ github.run_id }}
          ${{ env.DOCKER_USERNAME }}/go-service:latest

  trivy-security-scan:
    runs-on: ubuntu-latest
    needs: docker-build-push
    env:
      DOCKER_USERNAME: lookatravi
    permissions:
      security-events: write
      contents: read
    steps:
    - name: Scan Java Image
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        image-ref: '${{ env.DOCKER_USERNAME }}/java-service:${{ github.run_id }}'
        severity: 'CRITICAL,HIGH'
        format: 'sarif'
        output: 'trivy-java.sarif'
        exit-code: '1'

    - name: Upload Java SARIF
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-java.sarif'
        category: 'java-scan'

    - name: Scan Python Image
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        image-ref: '${{ env.DOCKER_USERNAME }}/python-service:${{ github.run_id }}'
        severity: 'CRITICAL,HIGH'
        format: 'sarif'
        output: 'trivy-python.sarif'
        exit-code: '1'

    - name: Upload Python SARIF
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-python.sarif'
        category: 'python-scan'

    - name: Scan Go Image
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        image-ref: '${{ env.DOCKER_USERNAME }}/go-service:${{ github.run_id }}'
        severity: 'CRITICAL,HIGH'
        format: 'sarif'
        output: 'trivy-go.sarif'
        exit-code: '1'

    - name: Upload Go SARIF
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-go.sarif'
        category: 'go-scan'

  update-k8s-manifests:
    runs-on: ubuntu-latest
    needs: trivy-security-scan
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Kubernetes Manifests
      run: |
        sed -i "/name: java-service/{n;s|image: .*|image: lookatravi/java-service:${{ github.run_id }}|}" k8s-manifest-all/all-services.yaml
        sed -i "/name: python-service/{n;s|image: .*|image: lookatravi/python-service:${{ github.run_id }}|}" k8s-manifest-all/all-services.yaml
        sed -i "/name: go-service/{n;s|image: .*|image: lookatravi/go-service:${{ github.run_id }}|}" k8s-manifest-all/all-services.yaml

    - name: Commit and Push Manifest Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add k8s-manifest-all/all-services.yaml
        git commit -m "CI: Update image tags to ${{ github.run_id }}" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/lookatravi/multi-lang-devops-project.git HEAD:main