name: Cleanup Old Docker Images

on:
  schedule:
    - cron: '0 0 * * 0'   # Every Sunday at midnight UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Clean Java Service images
      run: |
        # Install required tools
        sudo apt-get update && sudo apt-get install -y jq curl

        # Get all tags for java-service
        TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/java-service/tags/?page_size=100" | jq -r '.results[].name')

        # Keep last 10 tags
        KEEP_TAGS=$(echo "$TAGS" | head -10)
        DELETE_TAGS=$(echo "$TAGS" | tail -n +11)

        # Delete old tags
        for TAG in $DELETE_TAGS; do
          echo "Deleting ${{ secrets.DOCKER_USERNAME }}/java-service:$TAG"
          curl -X DELETE \
            -H "Authorization: Bearer $(curl -s -H "Content-Type: application/json" \
            -X POST \
            -d '{"username": "'"${{ secrets.DOCKER_USERNAME }}"'", "password": "'"${{ secrets.DOCKER_TOKEN }}"'"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)" \
            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/java-service/tags/$TAG/"
        done

    - name: Clean Python Service images
      run: |
        TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/python-service/tags/?page_size=100" | jq -r '.results[].name')
        KEEP_TAGS=$(echo "$TAGS" | head -10)
        DELETE_TAGS=$(echo "$TAGS" | tail -n +11)

        for TAG in $DELETE_TAGS; do
          echo "Deleting ${{ secrets.DOCKER_USERNAME }}/python-service:$TAG"
          curl -X DELETE \
            -H "Authorization: Bearer $(curl -s -H "Content-Type: application/json" \
            -X POST \
            -d '{"username": "'"${{ secrets.DOCKER_USERNAME }}"'", "password": "'"${{ secrets.DOCKER_TOKEN }}"'"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)" \
            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/python-service/tags/$TAG/"
        done

    - name: Clean Go Service images
      run: |
        TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/go-service/tags/?page_size=100" | jq -r '.results[].name')
        KEEP_TAGS=$(echo "$TAGS" | head -10)
        DELETE_TAGS=$(echo "$TAGS" | tail -n +11)

        for TAG in $DELETE_TAGS; do
          echo "Deleting ${{ secrets.DOCKER_USERNAME }}/go-service:$TAG"
          curl -X DELETE \
            -H "Authorization: Bearer $(curl -s -H "Content-Type: application/json" \
            -X POST \
            -d '{"username": "'"${{ secrets.DOCKER_USERNAME }}"'", "password": "'"${{ secrets.DOCKER_TOKEN }}"'"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)" \
            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/go-service/tags/$TAG/"
        done